name: payable_ipg_flutter
description: PAYable IPG SDK for Flutter
version: 2.0.4
repository: https://github.com/payable/flutter-ipg
homepage: https://flutter-ipg.payable.lk

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  http: ^1.2.1
  package_info_plus: ^8.0.2
  crypto: ^3.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2